### PR TITLE
Docs: fix paths for documentation builds to adapt to ROCR new folder structure

### PR DESCRIPTION
**Pull request by yhuiYH**

### CODE REVIEW

**Comment by yhuiYH** [comment]
@dishikre I think these are the doc changes we need in amd-staging now.  @samjwu as FYI, for the ROCR-Runtime repo changes

**Review by dayatsin-amd — CHANGES_REQUESTED** [review]
Changes look good to me. 

Can we squash these 2 commits:
fix path to requirements. Typo
fix path to conf. Typo

With:
docs: path adjustments to allow documentation to build again

**Comment by yhuiYH** [comment]
Done.  Commits are squashed.

**Review by dayatsin-amd — APPROVED** [review]
Looks good to me - approved.

Please do not submit changes. We will pull from internal gerrit

**Comment by yhuiYH** [comment]
> Looks good to me - approved.
> 
> Please do not submit changes. We will pull from internal gerrit

Perfect.  Yes, I know you'll pull it internal.  I will **not** merge it.

**Comment by yhuiYH** [comment]
Closing because this change has been pushed out to default branch now.

**Pull request closed without merging**
