### PR TITLE
Port doc reorg to doc 6.1.2

### PR DESCRIPTION
**Pull request by yhuiYH**

### CODE REVIEW

**Comment by dayatsin-amd** [comment]
Is there a way I can see a rendered view of the documents generated?

**Comment by yhuiYH** [comment]
I showed @dayatsin-amd how to access the preview build.

**Comment by dayatsin-amd** [comment]
Thanks @yhuiYH 

One issue, the API page here:

https://advanced-micro-devices-demo--217.com.readthedocs.build/projects/ROCR-Runtime/en/217/api-reference/api.html
 
These are generated from hsa.h file (which is correct).  But we also have another set of APIs defined in hsa_ext_amd.h:
 
https://github.com/ROCm/ROCR-Runtime/blob/master/src/inc/hsa_ext_amd.h

**Comment by yhuiYH** [comment]
> Thanks @yhuiYH
> 
> One issue, the API page here:
> 
> https://advanced-micro-devices-demo--217.com.readthedocs.build/projects/ROCR-Runtime/en/217/api-reference/api.html
> 
> These are generated from hsa.h file (which is correct). But we also have another set of APIs defined in hsa_ext_amd.h:
> 
> https://github.com/ROCm/ROCR-Runtime/blob/master/src/inc/hsa_ext_amd.h

The original API page is: https://rocm.docs.amd.com/projects/ROCR-Runtime/en/latest/api.html.  Is the content from https://github.com/ROCm/ROCR-Runtime/blob/master/src/inc/hsa_ext_amd.h ever included here?  

If not, @lpaoletti @amitkumar-amd can probably have someone work further with you on that.

**Comment by dayatsin-amd** [comment]
It seems this was missed from before. We can include hsa_ext_amd.h in another PR.

**Comment by dayatsin-amd** [comment]
Other than that. New documentation page looks ok to me. Thank you for working on this. If you want to start merging this change, we can remove the 'draft' flag.

**Review by dayatsin-amd — APPROVED** [review]

**Pull request merged**
