### PR TITLE
rocr: Adding pointer to the owner driver in Agent class

### PR DESCRIPTION
**Pull request by ypapadop-amd**
This PR establishes the association between `Agent` objects and `Driver` objects via a pointer (`Agent::driver_`), rather than an enum (`Agent::driver_type`) to avoid look-ups of the `Driver` object during use outside of construction.

### CODE REVIEW

**Review by atgutier — APPROVED** [review]

**Review by dayatsin-amd — APPROVED** [review]

**Comment by dayatsin-amd** [comment]
!verify

**Comment by atgutier** [comment]
Can we merge this in?

**Comment by dayatsin-amd** [comment]
!verify

**Comment by dayatsin-amd** [comment]
@atgutier  yes, merge is in progress. 
The internal CI failed for some other reason. Waiting for tests to pass to merge.

https://gerrit-git.amd.com/c/hsa/ec/rocr-runtime/+/1143970

**Comment by dayatsin-amd** [comment]
Merged into amd-staging branch

**Pull request closed without merging**
