### PR TITLE
ROCm 6.0.0 updates

### PR DESCRIPTION
**Pull request by dayatsin-amd**

### CODE REVIEW

**Comment by sjnewbury** [comment]
This breaks at least GFX900.

This is *probably* the right fix:

```
diff --git a/src/core/runtime/amd_blit_sdma.cpp b/src/core/runtime/amd_blit_sdma.cpp
index 830cb98..fa0a732 100644
--- a/src/core/runtime/amd_blit_sdma.cpp
+++ b/src/core/runtime/amd_blit_sdma.cpp
@@ -149,7 +149,7 @@ hsa_status_t BlitSdma<RingIndexTy, HwIndexMonotonic, SizeToCountOffset, useGCR>:
   }

   // Some GFX9 devices require a minimum of 64 DWORDS per ring buffer submission.
-  if (agent_->isa()->GetVersion() >= core::Isa::Version(9, 0, 0) &&
+  if (agent_->isa()->GetVersion() > core::Isa::Version(9, 0, 2) &&
       (agent_->isa()->GetVersion() <= core::Isa::Version(9, 0, 4) ||
        agent_->isa()->GetVersion() == core::Isa::Version(9, 0, 12))) {
     min_submission_size_ = 256;

```

**Comment by shwetagkhatri** [comment]
Hi @sjnewbury ,
To address this concern correctly - could you tell me which AMD GPU you are facing an issue with? Could you paste the output of rocminfo - /opt/rocm/bin/rocminfo ? 
Also if possible explain or provide a simplified version of your test case?

**Comment by sjnewbury** [comment]
The Raven Ridge testing was done with a full ROCm 6.0.2 built specifically for GFX902 only.

**Comment by sjnewbury** [comment]
After applying the alignment fix patch to from https://github.com/ROCm/clr/issues/18 along with the fix above clr now works with both r900 and r902.

**Comment by shwetagkhatri** [comment]
@sjnewbury , Thank you for all these information. We will update the patch with added support for gfx902 - 
+  if (agent_->isa()->GetVersion() > core::Isa::Version(9, 0, 2) - 
Will merge this from internal AMD branch and it should be available in ROCm 6.1 release.

**Comment by sjnewbury** [comment]
@shwetagkhatri , thanks, that's great!

**Comment by shwetagkhatri** [comment]
Hi @sjnewbury,
For the GFX900 issue - could you please run your test with the follow patch? This fixes the pad_size address -
```
+++ b/opensrc/hsa-runtime/core/runtime/amd_blit_sdma.cpp
@@ -471,0 +472 @@ hsa_status_t BlitSdma<RingIndexTy, HwIndexMonotonic, SizeToCountOffset, useGCR>:
 + command_addr += trap_command_size_;
@@ -482 +483 @@ hsa_status_t BlitSdma<RingIndexTy, HwIndexMonotonic, SizeToCountOffset, useGCR>:
- dword_command_addr[total_command_size/4] = (pad_size/4 - 1) << 16;
+ dword_command_addr[0] = (pad_size/4 - 1) << 16;
```

**Comment by sjnewbury** [comment]
@shwetagkhatri As an alternative (correct) fix? So instead of my current patch?

**Comment by shwetagkhatri** [comment]
As an alternative (correct) fix. Just on top of - ROCm 6.0.0+ rocm-opencl-runtime, without your current patch.

**Comment by sjnewbury** [comment]
@shwetagkhatri , sorry for taking so long to test this.  I've tested it on my GFX902 laptop and it seems to be working.

**Pull request merged**
